feat: git clone & lfs
blib-la/captain pull request #67
Opened 2024-02-28 00:01 UTC by TimPietrusky

## Motivation

* Integrated GitPortable for Windows
* Use clone or lfs to interact with git

2024-02-28 10:14 UTC, pixelass requested changes

2024-02-28 10:14 UTC, pixelass commented on package.json
>      "test:e2e": "xvfb-run --auto-servernum --server-args=\"-screen 0 1280x960x24\" -- npx playwright test",
```suggestion
    "test:e2e": "xvfb-run --auto-servernum --server-args=\"-screen 0 1280x960x24\" -- npx cross-env TEST_ENV=test npx playwright test",
```

2024-02-28 10:14 UTC, pixelass commented on playwright/git.test.ts
> +			NODE_ENV: "development",
```suggestion
```

2024-02-28 10:14 UTC, pixelass commented on src/electron/future/utils/git.ts
> +				const percent = Number.parseFloat(progressMatch[1]);
```suggestion
				const percent = Number.parseFloat(progressMatch[1]) / 100;
```

2024-02-28 10:14 UTC, pixelass commented on src/electron/future/utils/git.ts
> +			const percent = Number.parseFloat(progressMatch[1]);
```suggestion
			const percent = Number.parseFloat(progressMatch[1]) / 100;
```

2024-02-28 10:14 UTC, pixelass commented on src/electron/future/utils/path-helpers.ts
> +	}
a getter should not create directories

2024-03-01 13:55 UTC, TimPietrusky commented on package.json
>      "test:e2e": "xvfb-run --auto-servernum --server-args=\"-screen 0 1280x960x24\" -- npx playwright test",
Thanks, done!

2024-03-01 13:56 UTC, TimPietrusky commented on playwright/git.test.ts
> +			NODE_ENV: "development",
Was removed.

2024-03-01 13:59 UTC, TimPietrusky commented on src/electron/future/utils/path-helpers.ts
> +	}
This was removed and a new helper was created.

2024-03-03 22:01 UTC, pixelass approved these changes
LGTM 🚀

2024-03-04 09:17 UTC, merged

2024-03-04 09:22 UTC, TimPietrusky commented
:tada: This PR is included in version 1.0.0-alpha.9 :tada:

The release is available on [GitHub release](https://github.com/blib-la/captain/releases/tag/v1.0.0-alpha.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: